# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/trusty64"

    # Set up Port forwarding
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 4430

    # Shared folders setup
    # config.vm.synced_folder "configfiles", "/var/configfiles"
    config.vm.synced_folder "../client/dist", "/vagrant/client"
    config.vm.synced_folder "../server", "/vagrant/server"

    # (Shell) Provisioning
    config.vm.provision "shell", path: "bootstrap.sh"
end
